-- -- after/plugin/cmp_tab.lua
-- local cmp = require('cmp')
--
-- -- run *after* the current event loop tick so it’s last-last
-- vim.schedule(function()
--   -- 1. Kill the built-in snippet Tab (0.10+)
--   for _, m in ipairs({ 'i', 's' }) do
--     pcall(vim.keymap.del, m, '<Tab>')
--   end
--
--   -- 2. Hand Tab / S-Tab / Enter to cmp
--   cmp.setup({
--     snippet = { expand = function() end },   -- no snippet engine
--     mapping = {
--       ['<Tab>'] = cmp.mapping(function(fb)
--         if cmp.visible() then
--           cmp.select_next_item()
--         else
--           cmp.complete()
--         end
--       end, { 'i', 's' }),
--
--       ['<S-Tab>'] = cmp.mapping(function(fb)
--         if cmp.visible() then
--           cmp.select_prev_item()
--         else
--           fb()
--         end
--       end, { 'i', 's' }),
--
--       ['<CR>'] = cmp.mapping.confirm({ select = true }),
--     },
--   })
-- end)
--
